import {randomBytes,createCipheriv,createDecipheriv,createHash} from 'node:crypto';
const ROOT=process.env.DRIVE_FOLDER_ID;
const ARCHIVE='.sixtysix-history',LAYOUT='.sixtysix-layout.json';
const hash=s=>createHash('sha256').update(s).digest('hex');
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(x=>x.includes('=')).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),x.slice(i+1)];}));}
function seal(value){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',Buffer.from(process.env.SESSION_SECRET,'hex'),iv);const body=Buffer.concat([c.update(JSON.stringify(value)),c.final()]);return Buffer.concat([iv,c.getAuthTag(),body]).toString('base64url');}
function unseal(value){try{const b=Buffer.from(value||'','base64url');const d=createDecipheriv('aes-256-gcm',Buffer.from(process.env.SESSION_SECRET,'hex'),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));const obj=JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]));if(obj.expires<Date.now())return null;return obj;}catch{return null;}}
function cookie(res,name,value,age){res.setHeader('Set-Cookie',`${name}=${value}; HttpOnly; Secure; SameSite=Lax; Path=/api; Max-Age=${age}`);}
async function token(body){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...body,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET})});if(!r.ok)fail('Google-Anmeldung bitte erneuern.',401);return r.json();}
async function readBody(req){if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const c of req){s+=c;if(Buffer.byteLength(s)>1100000)fail('Die Datei darf höchstens 1 MB groß sein.',413);}try{return JSON.parse(s||'{}');}catch{fail('Ungültige Anfrage.');}}
export function validateFile(body){if(typeof body.content!=='string'||Buffer.byteLength(body.content)>1048576)fail('Markdown-Inhalt muss Text unter 1 MB sein.');if(body.name!==undefined&&(!/^[^/\\\x00-\x1f]+\.md$/i.test(body.name)||body.name.startsWith('.')||body.name.length>180))fail('Bitte einen gültigen Dateinamen mit .md verwenden.');}
export async function driveClient(access){
 async function request(path,options={},raw=false){const r=await fetch('https://www.googleapis.com/'+path,{...options,headers:{Authorization:`Bearer ${access}`,...options.headers}});if(!r.ok){if(r.status===412)fail('Die Datei wurde inzwischen geändert. Dein Entwurf bleibt erhalten. Bitte den aktuellen Stand vergleichen.',409);if(r.status===401)fail('Google-Anmeldung bitte erneuern.',401);if(r.status===403){let detail={};try{detail=await r.json();}catch{}const reasons=[...(detail.error?.errors||[]).map(x=>x.reason),...(detail.error?.details||[]).map(x=>x.reason)].filter(x=>typeof x==='string'&&/^[a-zA-Z0-9_]{1,80}$/.test(x));const hints={accessNotConfigured:'Aktiviere die Google Drive API im Google-Cloud-Projekt des verwendeten OAuth-Clients.',SERVICE_DISABLED:'Aktiviere die Google Drive API im Google-Cloud-Projekt des verwendeten OAuth-Clients.',insufficientPermissions:'Melde dich erneut an und erlaube den angeforderten Google-Drive-Zugriff.',ACCESS_TOKEN_SCOPE_INSUFFICIENT:'Melde dich erneut an und erlaube den angeforderten Google-Drive-Zugriff.',insufficientFilePermissions:'Das angemeldete Konto braucht Bearbeitungszugriff auf den Projektordner und dessen Dateien.',domainPolicy:'Die Google-Workspace-Verwaltung blockiert den Drive-Zugriff dieser App.',storageQuotaExceeded:'Der Google-Drive-Speicher des Kontos ist voll.',userRateLimitExceeded:'Google begrenzt die Anfragen vorübergehend. Bitte später erneut versuchen.',rateLimitExceeded:'Google begrenzt die Anfragen vorübergehend. Bitte später erneut versuchen.'};const hint=reasons.map(x=>hints[x]).find(Boolean)||'Google lehnt diese Drive-Anfrage ab.';fail(hint+' [Drive 403: '+(reasons.join(', ')||'unknown')+'; '+(options.method||'GET')+' '+(path.startsWith('upload/')?'Datei speichern':path.includes('alt=media')?'Datei lesen':options.method==='POST'?'Datei oder Ordner erstellen':'Ordnerinhalt lesen')+']',403);}fail('Google Drive konnte die Anfrage nicht abschließen ('+r.status+').',502);}if(raw)return {content:await r.text(),etag:r.headers.get('etag')};return r.status===204?{}:r.json();}
 async function list(q){const rows=[];let page='';do{const params=new URLSearchParams({q:`trashed = false and (${q})`,pageSize:'100',fields:'nextPageToken,files(id,name,mimeType,parents,modifiedTime,version,headRevisionId,appProperties)',...(page?{pageToken:page}:{})});const d=await request('drive/v3/files?'+params);rows.push(...d.files);page=d.nextPageToken;}while(page);return rows;}
 async function create(name,parent,content,mime='text/markdown',props={}){const boundary='ss'+randomBytes(16).toString('hex');const metadata={name,parents:[parent],mimeType:mime,appProperties:props};const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${mime}; charset=UTF-8\r\n\r\n${content}\r\n--${boundary}--`;return request('upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime,version',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});}
 async function folder(name,parent){const files=await list(`'${parent}' in parents and mimeType = 'application/vnd.google-apps.folder'`);const found=files.find(f=>f.name===name);if(found)return found.id;return(await request('drive/v3/files?fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parents:[parent],mimeType:'application/vnd.google-apps.folder'})})).id;}
 async function content(id,guarded=false){if(!guarded)return request('drive/v3/files/'+encodeURIComponent(id)+'?alt=media',{},true);const path='drive/v2/files/'+encodeURIComponent(id)+'?fields=id,etag,version,modifiedDate';const before=await request(path);const raw=await request('drive/v3/files/'+encodeURIComponent(id)+'?alt=media',{},true);const after=await request(path);if(!before.etag||before.etag!==after.etag||before.version!==after.version)fail('Die Datei wurde während des Lesens geändert. Bitte erneut speichern; dein Entwurf bleibt erhalten.',409);return {...raw,etag:after.etag,version:after.version,modifiedTime:after.modifiedDate};}
 async function update(id,value,etag){if(!etag)fail('Google Drive liefert keinen sicheren Versionsvergleich. Speichern wurde zum Schutz vor Überschreiben abgebrochen.',503);const next=await request('upload/drive/v2/files/'+encodeURIComponent(id)+'?uploadType=media&newRevision=true&fields=id,version,modifiedDate',{method:'PUT',headers:{'Content-Type':'text/plain; charset=UTF-8','If-Match':etag},body:value});return {...next,modifiedTime:next.modifiedDate};}
 return {list,create,folder,content,update,request};
}
async function catalog(d){const folders=[{id:ROOT,name:'SixtySix',path:'',parent:null}],files=[];async function walk(parent,path,depth){if(depth>30)fail('Die Ordnerstruktur ist zu tief.',422);for(const f of await d.list(`'${parent}' in parents`)){if(f.name===ARCHIVE||f.name===LAYOUT)continue;const p=path?path+'/'+f.name:f.name;if(f.mimeType==='application/vnd.google-apps.folder'){folders.push({...f,path:p,parent});await walk(f.id,p,depth+1);}else if(/\.md$/i.test(f.name)&&!f.mimeType.startsWith('application/vnd.google-apps.'))files.push({...f,path:p,parent});}}await walk(ROOT,'',0);return{folders,files};}
export function uniqueRevisions(revisions){const result=[];const seen=new Map();for(const r of [...revisions].sort((a,b)=>b.time.localeCompare(a.time))){const parsed=Date.parse(r.time);const key=JSON.stringify([r.sourceId,r.content,Number.isFinite(parsed)?parsed:r.time]);const previous=seen.get(key);if(previous){if(previous.author==='Drive'&&r.author&&r.author!=='Drive')Object.assign(previous,r);continue;}const copy={...r};seen.set(key,copy);result.push(copy);}return result;}
async function archive(d,folderId,f,content,author='Drive',time=f.modifiedTime){const source=String(f.version||hash(content));const existing=await d.list(`'${folderId}' in parents and appProperties has { key='sourceId' and value='${f.id}' } and appProperties has { key='sourceVersion' and value='${source}' }`);if(existing.length)return;if(time){const rows=await d.list(`'${folderId}' in parents and appProperties has { key='sourceId' and value='${f.id}' }`);for(const row of rows){const previous=JSON.parse((await d.content(row.id)).content);if(previous.content===content&&Date.parse(previous.time)===Date.parse(time)&&(author==='Drive'||previous.author===author))return;}}await d.create(f.id+'-'+source+'.json',folderId,JSON.stringify({sourceId:f.id,id:source,content,time:time||new Date().toISOString(),author}), 'application/json',{sourceId:f.id,sourceVersion:source});}
export default async function handler(req,res,route){
 const send=(code,data)=>{res.statusCode=code;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data));};res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');
 try{
  const ready=['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','ALLOWED_EMAIL','APP_ORIGIN','DRIVE_FOLDER_ID'].every(x=>process.env[x])&&/^[a-f\d]{64}$/i.test(process.env.SESSION_SECRET||'');
  if(!ready){const missing=['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','ALLOWED_EMAIL','APP_ORIGIN','DRIVE_FOLDER_ID'].filter(x=>!process.env[x]);if(!/^[a-f\d]{64}$/i.test(process.env.SESSION_SECRET||''))missing.push('SESSION_SECRET (64 Hex-Zeichen)');return send(503,{error:'Die Google-Anbindung ist noch nicht vollständig eingerichtet. In Vercel fehlen oder sind ungültig: '+missing.join(', ')+'. Nach dem Eintragen bitte erneut bereitstellen (Redeploy).'});}
  const origin=process.env.APP_ORIGIN.replace(/\/$/,'');const url=new URL(req.url,origin),action=route||url.pathname.split('/').filter(Boolean).at(-1);
  if(action==='login'&&req.method==='GET'){const state=randomBytes(24).toString('hex');cookie(res,'ss_oauth',seal({state,expires:Date.now()+600000}),600);res.statusCode=302;res.setHeader('Location','https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:origin+'/api/callback',response_type:'code',scope:'openid email https://www.googleapis.com/auth/drive',state,access_type:'offline',prompt:'consent'}));return res.end();}
  if(action==='callback'&&req.method==='GET'){if(url.searchParams.has('error'))fail('Google hat die Anmeldung nicht abgeschlossen. Bitte prüfe den Testnutzer und die angeforderten Berechtigungen.',401);const pending=unseal(cookies(req).ss_oauth);if(!pending||pending.state!==url.searchParams.get('state')||!url.searchParams.get('code'))fail('Anmeldung abgelaufen. Bitte erneut anmelden.',401);const t=await token({code:url.searchParams.get('code'),grant_type:'authorization_code',redirect_uri:origin+'/api/callback'});const info=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${t.access_token}`}});if(!info.ok)fail('Google-Konto konnte nicht geprüft werden.',401);const user=await info.json();if(!user.email_verified||user.email.toLowerCase()!==process.env.ALLOWED_EMAIL.toLowerCase())fail('Dieses Google-Konto hat keinen Zugriff auf diese Anwendung.',403);if(!t.refresh_token)fail('Google-Zugriff bitte neu bestätigen.',401);cookie(res,'ss_session',seal({refresh:t.refresh_token,email:user.email,expires:Date.now()+30*86400000}),30*86400);res.statusCode=302;res.setHeader('Location',origin);return res.end();}
  const session=unseal(cookies(req).ss_session);if(!session||session.email.toLowerCase()!==process.env.ALLOWED_EMAIL.toLowerCase())fail('Melde dich an, um deine Dateien zu öffnen.',401);
  if(!['GET','POST'].includes(req.method))fail('Methode nicht erlaubt.',405);
  if(req.method==='POST'&&(req.headers.origin!==origin||req.headers['x-sixtysix']!=='1'))fail('Anfrage nicht erlaubt.',403);
  const t=await token({refresh_token:session.refresh,grant_type:'refresh_token'}),d=await driveClient(t.access_token),cat=await catalog(d);
  let archiveId;async function historyFolder(){return archiveId??=await d.folder(ARCHIVE,ROOT);}
  if(action==='state'&&req.method==='GET'){
   const files=[];const historyRoot=await historyFolder();for(const f of cat.files){const raw=await d.content(f.id);await archive(d,historyRoot,f,raw.content);files.push({...f,content:raw.content});}
   const saved=await d.list(`'${ROOT}' in parents and name = '${LAYOUT}'`);let layout={};if(saved.length){try{layout=JSON.parse((await d.content(saved[0].id)).content);}catch{fail('Die gespeicherte Anordnung konnte nicht gelesen werden.',502);}}
   return send(200,{files,folders:cat.folders,layout:layout.positions||{},collapsed:layout.collapsed||[],mode:'drive'});
  }
  const body=req.method==='POST'?await readBody(req):{};
  if(action==='layout'&&req.method==='POST'){const allowed=new Set([...cat.files,...cat.folders].map(f=>f.id));const positions={};for(const[id,p]of Object.entries(body.positions||{})){if(allowed.has(id)&&Number.isFinite(p.x)&&Number.isFinite(p.y))positions[id]={x:p.x,y:p.y};}const value=JSON.stringify({positions,collapsed:(body.collapsed||[]).filter(x=>allowed.has(x))});const saved=await d.list(`'${ROOT}' in parents and name = '${LAYOUT}'`);if(saved.length){const raw=await d.content(saved[0].id,true);await d.update(saved[0].id,value,raw.etag);}else await d.create(LAYOUT,ROOT,value,'application/json');return send(200,{ok:true});}
  if(action==='create'&&req.method==='POST'){validateFile(body);if(!cat.folders.some(f=>f.id===body.parent))fail('Ordner nicht gefunden.',404);if(cat.files.some(f=>f.parent===body.parent&&f.name===body.name))fail('Diese Datei existiert bereits.',409);const f=await d.create(body.name,body.parent,body.content);await archive(d,await historyFolder(),f,body.content,session.email);return send(201,{id:f.id});}
  const id=body.id||url.searchParams.get('id'),f=cat.files.find(x=>x.id===id);if(!f)fail('Datei nicht gefunden.',404);
  if(action==='history'&&req.method==='GET'){
   const root=await historyFolder();const raw=await d.content(f.id);await archive(d,root,f,raw.content);
   const rows=(await d.list(`'${root}' in parents`)).filter(row=>row.name.startsWith(f.id+'-')&&row.name.endsWith('.json'));const revisions=[];for(const row of rows){const r=JSON.parse((await d.content(row.id)).content);if(r.sourceId===f.id)revisions.push(r);}return send(200,{revisions:uniqueRevisions(revisions)});
  }
  if(action==='save'&&req.method==='POST'){
   validateFile(body);if(typeof body.expected!=='string')fail('Ausgangsstand fehlt.');const raw=await d.content(f.id,true);if(raw.content!==body.expected)fail('Die Datei wurde inzwischen geändert. Dein Entwurf bleibt erhalten. Bitte den aktuellen Stand vergleichen.',409);
   const root=await historyFolder();await archive(d,root,{...f,version:raw.version,modifiedTime:raw.modifiedTime},raw.content);const next=await d.update(id,body.content,raw.etag);try{await archive(d,root,next,body.content,session.email);}catch{fail('Datei wurde gespeichert, aber die Archivierung ist fehlgeschlagen. Bitte die Historie erneut öffnen.',503);}return send(200,{ok:true});
  }
  fail('Nicht gefunden.',404);
 }catch(e){send(e.status||500,{error:e.status?e.message:'Die Anfrage konnte nicht abgeschlossen werden.'});}
}
